# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1, verbose_name='文章狀態')),
                ('abstract', models.CharField(blank=True, help_text='空白，則為前30字', max_length=30, null=True, verbose_name='摘要')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='瀏覽量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='讚數')),
                ('topped', models.BooleanField(default=False, verbose_name='置頂')),
            ],
            options={
                'ordering': ['-last_modified_time'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='類名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='修改時間')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.Category', verbose_name='分類'),
        ),
    ]
